version: "3"

services:

  php:
    container_name: ${APP_NAME}-php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
    networks:
      - default

  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    depends_on:
      - php
    volumes:
      - .:/var/www/html
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
      - '${NGINX_HOST_HTTPS_PORT}:443'
    networks:
      - default

networks:
  default:
